In [5]:
import pandas as pd
df = pd.DataFrame([['sample_1', 'sample_2', 0.2],
                   ['sample_1', 'sample_3', 0.5],
                   ['sample_2', 'sample_4', 0.8]],
                  columns=['SampleA', 'SampleB', 'Num_Differences'])
df

SampleA   SampleB  Num_Differences
0  sample_1  sample_2              0.2
1  sample_1  sample_3              0.5
2  sample_2  sample_4              0.8

In [10]:
# make unique, sorted, common index
idx = sorted(set(df['SampleA']).union(df['SampleB']))

# reshape
df = (df.pivot(index='SampleA', columns='SampleB', values='Num_Differences')
   .reindex(index=idx, columns=idx)
   .fillna(0, downcast='infer')
   .pipe(lambda x: x+x.values.T)
 )
print(df)

SampleB   sample_1  sample_2  sample_3  sample_4
SampleA                                         
sample_1       0.0       0.2       0.5       0.0
sample_2       0.2       0.0       0.0       0.8
sample_3       0.5       0.0       0.0       0.0
sample_4       0.0       0.8       0.0       0.0


In [6]:
#importing necessary packages
import numpy as np  
import scipy
import matplotlib.pyplot as plt
from sklearn.metrics import pairwise_distances #jaccard diss.
from sklearn import manifold  # multidimensional scaling
foods_binary = np.random.randint(2, size=(100, 10)) #initial dataset
print(foods_binary.shape)

(100, 10)


In [7]:
dis_matrix = pairwise_distances(foods_binary, metric = 'jaccard')
print(dis_matrix)

[[0.         0.75       0.71428571 ... 0.75       0.5        0.57142857]
 [0.75       0.         0.875      ... 0.75       0.5        0.88888889]
 [0.71428571 0.875      0.         ... 0.875      0.6        0.71428571]
 ...
 [0.75       0.75       0.875      ... 0.         0.5        0.57142857]
 [0.5        0.5        0.6        ... 0.5        0.         0.5       ]
 [0.57142857 0.88888889 0.71428571 ... 0.57142857 0.5        0.        ]]


/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/pairwise.py:1875: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


In [33]:
import pandas as pd
df = pd.DataFrame([['sample_1', 'sample_2', 0.2],
                   ['sample_1', 'sample_3', 0.5],
                   ['sample_2', 'sample_4', 0.8]],
                  columns=['SampleA', 'SampleB', 'Num_Differences'])


# make unique, sorted, common index
idx = sorted(set(df['SampleA']).union(df['SampleB']))

# reshape
df = (df.pivot(index='SampleA', columns='SampleB', values='Num_Differences')
   .reindex(index=idx, columns=idx)
   .fillna(0, downcast='infer')
   .pipe(lambda x: x+x.values.T)
 )

df = df.to_numpy().tolist()
df = ''.join(str(df).split(','))
df = eval(df)
df

SyntaxError: invalid syntax (<string>, line 1)

In [28]:
mds_model = manifold.MDS(n_components = 2, random_state = 123,
    dissimilarity = 'precomputed')
mds_fit = mds_model.fit(matrix)  
mds_coords = mds_model.fit_transform(matrix) 
                                                                                                                                  
food_names = ['sample 1', 'sample 2', 'sample 3', 'sample 4']
plt.figure()
plt.scatter(mds_coords[:,0],mds_coords[:,1],
    facecolors = 'none', edgecolors = 'none')  # points in white (invisible)
labels = food_names
for label, x, y in zip(labels, mds_coords[:,0], mds_coords[:,1]):
    plt.annotate(label, (x,y), xycoords = 'data')
plt.xlabel('First Dimension')
plt.ylabel('Second Dimension')
plt.title('Dissimilarity among food items')    
plt.show()


ValueError: Expected 2D array, got scalar array instead:
array=[[0.0 0.2 0.5 0.0] [0.2 0.0 0.0 0.8] [0.5 0.0 0.0 0.0] [0.0 0.8 0.0 0.0]].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.