In [1]:
import pandas as pd

df0_phase5 = pd.read_csv('final-bogota-0-phase5.csv')
df0_phase5 = df0_phase5.loc[:, ~df0_phase5.columns.str.contains('^Unnamed')]
df0_phase5.head(5)

Project                Hack       Student  Total Score  \
0  lfvalderrama  Bogota-Hack-0-2017  lfvalderrama       352.92   
1   Judgarciani  Bogota-Hack-0-2017   Judgarciani       325.00   
2     bsgarciac  Bogota-Hack-0-2017     bsgarciac       320.83   
3      Moimolcp  Bogota-Hack-0-2017      Moimolcp       304.17   
4     mnguzmanc  Bogota-Hack-0-2017     mnguzmanc       290.00   

   The % of participants whose total score below your score      Phase  
0                                              98.04         5th Phase  
1                                              96.08         5th Phase  
2                                              94.12         5th Phase  
3                                              92.16         5th Phase  
4                                              90.20         5th Phase

In [2]:
df0_phase5['Total Score'].mean()
df0_phase5['Total Score'].median()

190.83

In [3]:
df1_phase5 = pd.read_csv('final-bogota-1-phase5.csv')
df1_phase5 = df1_phase5.loc[:, ~df1_phase5.columns.str.contains('^Unnamed')]
df1_phase5.head(5)

Project                Hack         Student  Total Score  \
0          oeroaq  Bogota-Hack-1-2017          oeroaq       357.50   
1      jonatan360  Bogota-Hack-1-2017      jonatan360       352.50   
2  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       345.00   
3      daandradec  Bogota-Hack-1-2017      daandradec       336.67   
4       djguzmanc  Bogota-Hack-1-2017       djguzmanc       334.17   

   The % of participants whose total score below your score      Phase  
0                                              97.67         5th Phase  
1                                              95.35         5th Phase  
2                                              93.02         5th Phase  
3                                              90.70         5th Phase  
4                                              88.37         5th Phase

In [4]:
df1_phase5['Total Score'].mean()
df1_phase5['Total Score'].median()

198.33

In [5]:
df2_phase5 = pd.read_csv('final-bogota-2-phase5.csv')
df2_phase5 = df2_phase5.loc[:, ~df2_phase5.columns.str.contains('^Unnamed')]
df2_phase5.head(5)

Project                Hack          Student  Total Score  \
0        xdanielsb  Bogota-Hack-2-2017        xdanielsb       357.50   
1          Gantiva  Bogota-Hack-2-2017          Gantiva       345.83   
2         leguzman  Bogota-Hack-2-2017         leguzman       339.17   
3  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       337.50   
4   cesarochoa2006  Bogota-Hack-2-2017   cesarochoa2006       326.67   

   The % of participants whose total score below your score      Phase  
0                                              97.62         5th Phase  
1                                              95.24         5th Phase  
2                                              92.86         5th Phase  
3                                              90.48         5th Phase  
4                                              88.10         5th Phase

In [6]:
df2_phase5['Total Score'].mean()
df2_phase5['Total Score'].median()

178.33

In [7]:
df3_phase5 = pd.read_csv('final-bogota-3-phase5.csv')
df3_phase5 = df3_phase5.loc[:, ~df3_phase5.columns.str.contains('^Unnamed')]
df3_phase5.head(5)

Project                Hack          Student  Total Score  \
0       NicolasPrr  Bogota-Hack-3-2017       NicolasPrr       360.83   
1  jscastelblancoh  Bogota-Hack-3-2017  jscastelblancoh       358.33   
2        juligarji  Bogota-Hack-3-2017        juligarji       355.00   
3      lacardenasv  Bogota-Hack-3-2017      lacardenasv       350.00   
4       jmalvarezd  Bogota-Hack-3-2017       jmalvarezd       348.75   

   The % of participants whose total score below your score      Phase  
0                                              97.62         5th Phase  
1                                              95.24         5th Phase  
2                                              92.86         5th Phase  
3                                              90.48         5th Phase  
4                                              88.10         5th Phase

In [8]:
df3_phase5['Total Score'].mean()
df3_phase5['Total Score'].median()

209.58

In [9]:
df0_phase4 = pd.read_csv('final-bogota-0-phase4.csv')
df0_phase4 = df0_phase4.loc[:, ~df0_phase4.columns.str.contains('^Unnamed')]
df0_phase4.head(5)

Project                Hack     Student  Total Score  \
0   bsgarciac  Bogota-Hack-0-2017   bsgarciac       313.33   
1   jdsuarezj  Bogota-Hack-0-2017   jdsuarezj       276.67   
2  capinillab  Bogota-Hack-0-2017  capinillab       251.67   
3   mnguzmanc  Bogota-Hack-0-2017   mnguzmanc       245.00   
4   camilo654  Bogota-Hack-0-2017   camilo654       243.33   

   The % of participants whose total score below your score      Phase  
0                                              98.04         4th Phase  
1                                              96.08         4th Phase  
2                                              94.12         4th Phase  
3                                              92.16         4th Phase  
4                                              88.24         4th Phase

In [10]:
df0_phase4['Total Score'].mean()
df0_phase4['Total Score'].median()

128.33

In [11]:
df1_phase4 = pd.read_csv('final-bogota-1-phase4.csv')
df1_phase4 = df1_phase4.loc[:, ~df1_phase4.columns.str.contains('^Unnamed')]
df1_phase4.head(5)

Project                Hack         Student  Total Score  \
0          oeroaq  Bogota-Hack-1-2017          oeroaq       350.00   
1      jonatan360  Bogota-Hack-1-2017      jonatan360       343.33   
2  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       333.33   
3      daandradec  Bogota-Hack-1-2017      daandradec       318.75   
4  diegoaguevarar  Bogota-Hack-1-2017  diegoaguevarar       312.50   

   The % of participants whose total score below your score      Phase  
0                                              97.67         4th Phase  
1                                              95.35         4th Phase  
2                                              93.02         4th Phase  
3                                              90.70         4th Phase  
4                                              88.37         4th Phase

In [12]:
df1_phase4['Total Score'].mean()
df1_phase4['Total Score'].median()

174.17

In [13]:
df2_phase4 = pd.read_csv('final-bogota-2-phase4.csv')
df2_phase4 = df2_phase4.loc[:, ~df2_phase4.columns.str.contains('^Unnamed')]
df2_phase4.head(5)

Project                Hack          Student  Total Score  \
0        fabianr23  Bogota-Hack-2-2017        fabianr23       358.33   
1       jhriverasa  Bogota-Hack-2-2017       jhriverasa       333.33   
2       JuanitoAli  Bogota-Hack-2-2017       JuanitoAli       325.00   
3  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       320.83   
4       Davsatu313  Bogota-Hack-2-2017       Davsatu313       300.83   

   The % of participants whose total score below your score      Phase  
0                                              97.62         4th Phase  
1                                              95.24         4th Phase  
2                                              92.86         4th Phase  
3                                              90.48         4th Phase  
4                                              88.10         4th Phase

In [14]:
df2_phase4['Total Score'].mean()
df2_phase4['Total Score'].median()

137.5

In [15]:
df3_phase4 = pd.read_csv('final-bogota-3-phase4.csv')
df3_phase4 = df3_phase4.loc[:, ~df3_phase4.columns.str.contains('^Unnamed')]
df3_phase4.head(5)

Project                Hack          Student  Total Score  \
0        juligarji  Bogota-Hack-3-2017        juligarji       358.33   
1       lgmoralesa  Bogota-Hack-3-2017       lgmoralesa       337.50   
2  jscastelblancoh  Bogota-Hack-3-2017  jscastelblancoh       316.67   
3    jumcorredorro  Bogota-Hack-3-2017    jumcorredorro       305.00   
4        lemartinp  Bogota-Hack-3-2017        lemartinp       300.83   

   The % of participants whose total score below your score      Phase  
0                                              97.62         4th Phase  
1                                              95.24         4th Phase  
2                                              92.86         4th Phase  
3                                              90.48         4th Phase  
4                                              88.10         4th Phase

In [16]:
df3_phase4['Total Score'].mean()
df3_phase4['Total Score'].median()

145.41500000000002

# Improvement Score Bogota 3

In [17]:
diff3 = df3_phase5['Total Score'] - df3_phase4['Total Score']
diff3.values

array([ 2.5 , 20.83, 38.33, 45.  , 47.92, 74.16, 80.83, 64.17, 67.5 ,
       81.67, 66.67, 83.34, 81.25, 73.34, 83.75, 80.  , 89.59, 82.5 ,
       80.  , 72.08, 63.75, 64.58, 75.  , 82.5 , 77.5 , 76.25, 70.  ,
       62.5 , 61.67, 45.84, 32.5 , 16.66, 28.33, 20.83, 25.  , 12.5 ,
        0.  , 75.  ,  0.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 2

In [18]:
diff2 = df2_phase5['Total Score'] - df2_phase4['Total Score']
diff2.values

array([-0.83, 12.5 , 14.17, 16.67, 25.84, 35.83, 41.04, 42.71, 80.83,
       80.  , 94.17, 91.46, 69.16, 65.83, 62.5 , 28.33, 66.67, 58.34,
       37.5 , 34.17, 40.83, 42.5 , 40.83, 34.16, 37.5 , 36.67, 37.5 ,
       30.  , 20.83, 17.5 , 18.33, 20.  , 25.  , 12.5 , 25.  , 50.  ,
       75.  , 45.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 1

In [19]:
diff1 = df1_phase5['Total Score'] - df1_phase4['Total Score']
diff1.values

array([ 7.5 ,  9.17, 11.67, 17.92, 21.67, 30.  , 37.71, 38.33, 36.67,
       35.  , 32.5 , 19.16,  4.17, -2.08, -4.17, 11.67, 12.5 , 14.17,
       33.34, 28.34, 24.16, 32.08, 33.33, 29.17, 33.33, 37.5 ,  7.5 ,
        5.  ,  0.  ,  0.  ,  5.  ,  9.17,  0.83,  7.5 , 12.5 , 12.5 ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 0

In [20]:
diff0 = df0_phase5['Total Score'] - df0_phase4['Total Score']
diff0.values

array([39.59, 48.33, 69.16, 59.17, 46.67, 33.34, 30.  , 43.34, 43.33,
       39.16, 38.34, 30.  , 33.33, 31.67, 30.42, 33.34, 36.67, 47.5 ,
       63.33, 62.5 , 55.83, 36.67, 41.66, 33.34, 16.66, 24.17, 16.66,
       17.5 , 37.5 ,  5.  , 25.  , 49.17,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ])

In [21]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(diff0, diff1, diff2, diff3)
print(fvalue, pvalue)

18.138769455075185 3.57343138982153e-10


In [23]:
len(df0_phase5.index)

39

In [25]:
len(df1_phase5.index)

41

In [26]:
len(df2_phase5.index)

41

In [27]:
len(df3_phase5.index)

42

In [28]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'score': [39.59, 48.33, 69.16, 59.17, 46.67, 33.34, 30.  , 43.34, 43.33,
       39.16, 38.34, 30.  , 33.33, 31.67, 30.42, 33.34, 36.67, 47.5 ,
       63.33, 62.5 , 55.83, 36.67, 41.66, 33.34, 16.66, 24.17, 16.66,
       17.5 , 37.5 ,  5.  , 25.  , 49.17,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0. , 7.5 ,  9.17, 11.67, 17.92, 21.67, 30.  , 37.71, 38.33, 36.67,
       35.  , 32.5 , 19.16,  4.17, -2.08, -4.17, 11.67, 12.5 , 14.17,
       33.34, 28.34, 24.16, 32.08, 33.33, 29.17, 33.33, 37.5 ,  7.5 ,
        5.  ,  0.  ,  0.  ,  5.  ,  9.17,  0.83,  7.5 , 12.5 , 12.5 ,
        0.  ,  0.  ,  0.  ,  0.  ,  0. , -0.83, 12.5 , 14.17, 16.67, 25.84, 35.83, 41.04, 42.71, 80.83,
       80.  , 94.17, 91.46, 69.16, 65.83, 62.5 , 28.33, 66.67, 58.34,
       37.5 , 34.17, 40.83, 42.5 , 40.83, 34.16, 37.5 , 36.67, 37.5 ,
       30.  , 20.83, 17.5 , 18.33, 20.  , 25.  , 12.5 , 25.  , 50.  ,
       75.  , 45.  ,  0.  ,  0.  ,  0. , 2.5 , 20.83, 38.33, 45.  , 47.92, 74.16, 80.83, 64.17, 67.5 ,
       81.67, 66.67, 83.34, 81.25, 73.34, 83.75, 80.  , 89.59, 82.5 ,
       80.  , 72.08, 63.75, 64.58, 75.  , 82.5 , 77.5 , 76.25, 70.  ,
       62.5 , 61.67, 45.84, 32.5 , 16.66, 28.33, 20.83, 25.  , 12.5 ,
        0.  , 75.  ,  0.  ,  0.  ,  0.  ,  0.  ],
                   'group': np.repeat([0, 1, 2, 3], repeats=[39, 41, 41, 42])})

In [30]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd


# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=df['score'],
                          groups=df['group'],
                          alpha=0.05)

#display results
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     0      1 -15.5127 0.0163 -28.9346 -2.0908   True
     0      2   6.9564 0.5313  -6.4656 20.3783  False
     0      3  21.2803  0.001   7.9365  34.624   True
     1      2   22.469  0.001    9.216 35.7221   True
     1      3  36.7929  0.001   23.619 49.9669   True
     2      3  14.3239 0.0272     1.15 27.4978   True
-----------------------------------------------------
