In [1]:
import pandas as pd

df0_phase5 = pd.read_csv('final-bogota-0-phase5.csv')
df0_phase5 = df0_phase5.loc[:, ~df0_phase5.columns.str.contains('^Unnamed')]
df0_phase5.head(5)

Project                Hack       Student  Total Score  \
0  lfvalderrama  Bogota-Hack-0-2017  lfvalderrama       352.92   
1   Judgarciani  Bogota-Hack-0-2017   Judgarciani       325.00   
2     bsgarciac  Bogota-Hack-0-2017     bsgarciac       320.83   
3      Moimolcp  Bogota-Hack-0-2017      Moimolcp       304.17   
4     mnguzmanc  Bogota-Hack-0-2017     mnguzmanc       290.00   

   The % of participants whose total score below your score      Phase  
0                                              98.04         5th Phase  
1                                              96.08         5th Phase  
2                                              94.12         5th Phase  
3                                              92.16         5th Phase  
4                                              90.20         5th Phase

In [2]:
df0_phase5['Total Score'].mean()
df0_phase5['Total Score'].median()

190.83

In [3]:
df1_phase5 = pd.read_csv('final-bogota-1-phase5.csv')
df1_phase5 = df1_phase5.loc[:, ~df1_phase5.columns.str.contains('^Unnamed')]
df1_phase5.head(5)

Project                Hack         Student  Total Score  \
0          oeroaq  Bogota-Hack-1-2017          oeroaq       357.50   
1      jonatan360  Bogota-Hack-1-2017      jonatan360       352.50   
2  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       345.00   
3      daandradec  Bogota-Hack-1-2017      daandradec       336.67   
4       djguzmanc  Bogota-Hack-1-2017       djguzmanc       334.17   

   The % of participants whose total score below your score      Phase  
0                                              97.67         5th Phase  
1                                              95.35         5th Phase  
2                                              93.02         5th Phase  
3                                              90.70         5th Phase  
4                                              88.37         5th Phase

In [4]:
df1_phase5['Total Score'].mean()
df1_phase5['Total Score'].median()

198.33

In [5]:
df2_phase5 = pd.read_csv('final-bogota-2-phase5.csv')
df2_phase5 = df2_phase5.loc[:, ~df2_phase5.columns.str.contains('^Unnamed')]
df2_phase5.head(5)

Project                Hack          Student  Total Score  \
0        xdanielsb  Bogota-Hack-2-2017        xdanielsb       357.50   
1          Gantiva  Bogota-Hack-2-2017          Gantiva       345.83   
2         leguzman  Bogota-Hack-2-2017         leguzman       339.17   
3  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       337.50   
4   cesarochoa2006  Bogota-Hack-2-2017   cesarochoa2006       326.67   

   The % of participants whose total score below your score      Phase  
0                                              97.62         5th Phase  
1                                              95.24         5th Phase  
2                                              92.86         5th Phase  
3                                              90.48         5th Phase  
4                                              88.10         5th Phase

In [6]:
df2_phase5['Total Score'].mean()
df2_phase5['Total Score'].median()

178.33

In [7]:
df3_phase5 = pd.read_csv('final-bogota-3-phase5.csv')
df3_phase5 = df3_phase5.loc[:, ~df3_phase5.columns.str.contains('^Unnamed')]
df3_phase5.head(5)

Project                Hack          Student  Total Score  \
0       NicolasPrr  Bogota-Hack-3-2017       NicolasPrr       360.83   
1  jscastelblancoh  Bogota-Hack-3-2017  jscastelblancoh       358.33   
2        juligarji  Bogota-Hack-3-2017        juligarji       355.00   
3      lacardenasv  Bogota-Hack-3-2017      lacardenasv       350.00   
4       jmalvarezd  Bogota-Hack-3-2017       jmalvarezd       348.75   

   The % of participants whose total score below your score      Phase  
0                                              97.62         5th Phase  
1                                              95.24         5th Phase  
2                                              92.86         5th Phase  
3                                              90.48         5th Phase  
4                                              88.10         5th Phase

In [8]:
df3_phase5['Total Score'].mean()
df3_phase5['Total Score'].median()

209.58

In [9]:
df0_phase4 = pd.read_csv('final-bogota-0-phase4.csv')
df0_phase4 = df0_phase4.loc[:, ~df0_phase4.columns.str.contains('^Unnamed')]
df0_phase4.head(5)

Project                Hack     Student  Total Score  \
0   bsgarciac  Bogota-Hack-0-2017   bsgarciac       313.33   
1   jdsuarezj  Bogota-Hack-0-2017   jdsuarezj       276.67   
2  capinillab  Bogota-Hack-0-2017  capinillab       251.67   
3   mnguzmanc  Bogota-Hack-0-2017   mnguzmanc       245.00   
4   camilo654  Bogota-Hack-0-2017   camilo654       243.33   

   The % of participants whose total score below your score      Phase  
0                                              98.04         4th Phase  
1                                              96.08         4th Phase  
2                                              94.12         4th Phase  
3                                              92.16         4th Phase  
4                                              88.24         4th Phase

In [10]:
df0_phase4['Total Score'].mean()
df0_phase4['Total Score'].median()

128.33

In [11]:
df1_phase4 = pd.read_csv('final-bogota-1-phase4.csv')
df1_phase4 = df1_phase4.loc[:, ~df1_phase4.columns.str.contains('^Unnamed')]
df1_phase4.head(5)

Project                Hack         Student  Total Score  \
0          oeroaq  Bogota-Hack-1-2017          oeroaq       350.00   
1      jonatan360  Bogota-Hack-1-2017      jonatan360       343.33   
2  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       333.33   
3      daandradec  Bogota-Hack-1-2017      daandradec       318.75   
4  diegoaguevarar  Bogota-Hack-1-2017  diegoaguevarar       312.50   

   The % of participants whose total score below your score      Phase  
0                                              97.67         4th Phase  
1                                              95.35         4th Phase  
2                                              93.02         4th Phase  
3                                              90.70         4th Phase  
4                                              88.37         4th Phase

In [12]:
df1_phase4['Total Score'].mean()
df1_phase4['Total Score'].median()

174.17

In [13]:
df2_phase4 = pd.read_csv('final-bogota-2-phase4.csv')
df2_phase4 = df2_phase4.loc[:, ~df2_phase4.columns.str.contains('^Unnamed')]
df2_phase4.head(5)

Project                Hack          Student  Total Score  \
0        fabianr23  Bogota-Hack-2-2017        fabianr23       358.33   
1       jhriverasa  Bogota-Hack-2-2017       jhriverasa       333.33   
2       JuanitoAli  Bogota-Hack-2-2017       JuanitoAli       325.00   
3  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       320.83   
4       Davsatu313  Bogota-Hack-2-2017       Davsatu313       300.83   

   The % of participants whose total score below your score      Phase  
0                                              97.62         4th Phase  
1                                              95.24         4th Phase  
2                                              92.86         4th Phase  
3                                              90.48         4th Phase  
4                                              88.10         4th Phase

In [14]:
df2_phase4['Total Score'].mean()
df2_phase4['Total Score'].median()

137.5

In [15]:
df3_phase4 = pd.read_csv('final-bogota-3-phase4.csv')
df3_phase4 = df3_phase4.loc[:, ~df3_phase4.columns.str.contains('^Unnamed')]
df3_phase4.head(5)

Project                Hack          Student  Total Score  \
0        juligarji  Bogota-Hack-3-2017        juligarji       358.33   
1       lgmoralesa  Bogota-Hack-3-2017       lgmoralesa       337.50   
2  jscastelblancoh  Bogota-Hack-3-2017  jscastelblancoh       316.67   
3    jumcorredorro  Bogota-Hack-3-2017    jumcorredorro       305.00   
4        lemartinp  Bogota-Hack-3-2017        lemartinp       300.83   

   The % of participants whose total score below your score      Phase  
0                                              97.62         4th Phase  
1                                              95.24         4th Phase  
2                                              92.86         4th Phase  
3                                              90.48         4th Phase  
4                                              88.10         4th Phase

In [16]:
df3_phase4['Total Score'].mean()
df3_phase4['Total Score'].median()

145.41500000000002

# Improvement Score Bogota 3

In [17]:
diff3 = df3_phase5['Total Score'] - df3_phase4['Total Score']
diff3.values

array([ 2.5 , 20.83, 38.33, 45.  , 47.92, 74.16, 80.83, 64.17, 67.5 ,
       81.67, 66.67, 83.34, 81.25, 73.34, 83.75, 80.  , 89.59, 82.5 ,
       80.  , 72.08, 63.75, 64.58, 75.  , 82.5 , 77.5 , 76.25, 70.  ,
       62.5 , 61.67, 45.84, 32.5 , 16.66, 28.33, 20.83, 25.  , 12.5 ,
        0.  , 75.  ,  0.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 2

In [18]:
diff2 = df2_phase5['Total Score'] - df2_phase4['Total Score']
diff2.values

array([-0.83, 12.5 , 14.17, 16.67, 25.84, 35.83, 41.04, 42.71, 80.83,
       80.  , 94.17, 91.46, 69.16, 65.83, 62.5 , 28.33, 66.67, 58.34,
       37.5 , 34.17, 40.83, 42.5 , 40.83, 34.16, 37.5 , 36.67, 37.5 ,
       30.  , 20.83, 17.5 , 18.33, 20.  , 25.  , 12.5 , 25.  , 50.  ,
       75.  , 45.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 1

In [19]:
diff1 = df1_phase5['Total Score'] - df1_phase4['Total Score']
diff1.values

array([ 7.5 ,  9.17, 11.67, 17.92, 21.67, 30.  , 37.71, 38.33, 36.67,
       35.  , 32.5 , 19.16,  4.17, -2.08, -4.17, 11.67, 12.5 , 14.17,
       33.34, 28.34, 24.16, 32.08, 33.33, 29.17, 33.33, 37.5 ,  7.5 ,
        5.  ,  0.  ,  0.  ,  5.  ,  9.17,  0.83,  7.5 , 12.5 , 12.5 ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

# Improvement Score Bogota 0

In [20]:
diff0 = df0_phase5['Total Score'] - df0_phase4['Total Score']
diff0.values

array([39.59, 48.33, 69.16, 59.17, 46.67, 33.34, 30.  , 43.34, 43.33,
       39.16, 38.34, 30.  , 33.33, 31.67, 30.42, 33.34, 36.67, 47.5 ,
       63.33, 62.5 , 55.83, 36.67, 41.66, 33.34, 16.66, 24.17, 16.66,
       17.5 , 37.5 ,  5.  , 25.  , 49.17,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ])

In [21]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(diff0, diff1, diff2, diff3)
print(fvalue, pvalue)

18.138769455075185 3.57343138982153e-10


In [22]:
len(df0_phase5.index)

39

In [23]:
len(df1_phase5.index)

41

In [24]:
len(df2_phase5.index)

41

In [25]:
len(df3_phase5.index)

42

In [26]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'score': [39.59, 48.33, 69.16, 59.17, 46.67, 33.34, 30.  , 43.34, 43.33,
       39.16, 38.34, 30.  , 33.33, 31.67, 30.42, 33.34, 36.67, 47.5 ,
       63.33, 62.5 , 55.83, 36.67, 41.66, 33.34, 16.66, 24.17, 16.66,
       17.5 , 37.5 ,  5.  , 25.  , 49.17,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0. , 7.5 ,  9.17, 11.67, 17.92, 21.67, 30.  , 37.71, 38.33, 36.67,
       35.  , 32.5 , 19.16,  4.17, -2.08, -4.17, 11.67, 12.5 , 14.17,
       33.34, 28.34, 24.16, 32.08, 33.33, 29.17, 33.33, 37.5 ,  7.5 ,
        5.  ,  0.  ,  0.  ,  5.  ,  9.17,  0.83,  7.5 , 12.5 , 12.5 ,
        0.  ,  0.  ,  0.  ,  0.  ,  0. , -0.83, 12.5 , 14.17, 16.67, 25.84, 35.83, 41.04, 42.71, 80.83,
       80.  , 94.17, 91.46, 69.16, 65.83, 62.5 , 28.33, 66.67, 58.34,
       37.5 , 34.17, 40.83, 42.5 , 40.83, 34.16, 37.5 , 36.67, 37.5 ,
       30.  , 20.83, 17.5 , 18.33, 20.  , 25.  , 12.5 , 25.  , 50.  ,
       75.  , 45.  ,  0.  ,  0.  ,  0. , 2.5 , 20.83, 38.33, 45.  , 47.92, 74.16, 80.83, 64.17, 67.5 ,
       81.67, 66.67, 83.34, 81.25, 73.34, 83.75, 80.  , 89.59, 82.5 ,
       80.  , 72.08, 63.75, 64.58, 75.  , 82.5 , 77.5 , 76.25, 70.  ,
       62.5 , 61.67, 45.84, 32.5 , 16.66, 28.33, 20.83, 25.  , 12.5 ,
        0.  , 75.  ,  0.  ,  0.  ,  0.  ,  0.  ],
                   'group': np.repeat([0, 1, 2, 3], repeats=[39, 41, 41, 42])})

In [27]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd


# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=df['score'],
                          groups=df['group'],
                          alpha=0.05)

#display results
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     0      1 -15.5127 0.0163 -28.9346 -2.0908   True
     0      2   6.9564 0.5313  -6.4656 20.3783  False
     0      3  21.2803  0.001   7.9365  34.624   True
     1      2   22.469  0.001    9.216 35.7221   True
     1      3  36.7929  0.001   23.619 49.9669   True
     2      3  14.3239 0.0272     1.15 27.4978   True
-----------------------------------------------------


In [28]:
df3_phase3 = pd.read_csv('final-bogota-3-phase3.csv')
df3_phase3 = df3_phase3.loc[:, ~df3_phase3.columns.str.contains('^Unnamed')]
df3_phase3.head(5)

Project                Hack        Student  Total Score  \
0  jumcorredorro  Bogota-Hack-3-2017  jumcorredorro       330.00   
1     lgmoralesa  Bogota-Hack-3-2017     lgmoralesa       310.00   
2       dduartec  Bogota-Hack-3-2017       dduartec       305.00   
3     jmalvarezd  Bogota-Hack-3-2017     jmalvarezd       275.00   
4    lacardenasv  Bogota-Hack-3-2017    lacardenasv       264.17   

   The % of participants whose total score below your score      Phase  
0                                              97.62         3rd Phase  
1                                              95.24         3rd Phase  
2                                              92.86         3rd Phase  
3                                              90.48         3rd Phase  
4                                              88.10         3rd Phase

In [29]:
df2_phase3 = pd.read_csv('final-bogota-2-phase3.csv')
df2_phase3 = df2_phase3.loc[:, ~df2_phase3.columns.str.contains('^Unnamed')]
df2_phase3.head(5)

Project                Hack          Student  Total Score  \
0        fabianr23  Bogota-Hack-2-2017        fabianr23       358.33   
1       Davsatu313  Bogota-Hack-2-2017       Davsatu313       320.83   
2       jhriverasa  Bogota-Hack-2-2017       jhriverasa       312.50   
3     jscontrerasp  Bogota-Hack-2-2017       joaortizro       305.00   
4  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       293.33   

   The % of participants whose total score below your score      Phase  
0                                              97.62         3rd Phase  
1                                              95.24         3rd Phase  
2                                              92.86         3rd Phase  
3                                              90.48         3rd Phase  
4                                              88.10         3rd Phase

In [30]:
df1_phase3 = pd.read_csv('final-bogota-1-phase3.csv')
df1_phase3 = df1_phase3.loc[:, ~df1_phase3.columns.str.contains('^Unnamed')]
df1_phase3.head(5)

Project                Hack         Student  Total Score  \
0  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       345.83   
1      falperezgo  Bogota-Hack-1-2017      falperezgo       338.33   
2      jonatan360  Bogota-Hack-1-2017      jonatan360       332.92   
3      dsbarrerag  Bogota-Hack-1-2017      dsbarrerag       325.00   
4  diegoaguevarar  Bogota-Hack-1-2017  diegoaguevarar       325.00   

   The % of participants whose total score below your score      Phase  
0                                              97.67         3rd Phase  
1                                              95.35         3rd Phase  
2                                              93.02         3rd Phase  
3                                              88.37         3rd Phase  
4                                              88.37         3rd Phase

In [31]:
df0_phase3 = pd.read_csv('final-bogota-0-phase3.csv')
df0_phase3 = df0_phase3.loc[:, ~df0_phase3.columns.str.contains('^Unnamed')]
df0_phase3.head(5)

Project                Hack       Student  Total Score  \
0     jdsuarezj  Bogota-Hack-0-2017     jdsuarezj       293.33   
1    JoseMolano  Bogota-Hack-0-2017    JoseMolano       289.17   
2     bsgarciac  Bogota-Hack-0-2017     bsgarciac       272.50   
3  lfvalderrama  Bogota-Hack-0-2017  lfvalderrama       250.42   
4     mnguzmanc  Bogota-Hack-0-2017     mnguzmanc       236.67   

   The % of participants whose total score below your score      Phase  
0                                              98.04         3rd Phase  
1                                              96.08         3rd Phase  
2                                              94.12         3rd Phase  
3                                              92.16         3rd Phase  
4                                              90.20         3rd Phase

# Improvement Score Bogota 3

In [32]:
diff3 = df3_phase4['Total Score'] - df3_phase3['Total Score']
diff3.values

array([ 28.33,  27.5 ,  11.67,  30.  ,  36.66,  20.  ,  34.17,  37.5 ,
        39.17,  35.83,  40.  ,  25.83,  26.67,  48.33,  37.5 ,  38.33,
        17.5 ,   5.  ,   5.84,   4.17,   9.16,  11.67,   0.  ,  -3.34,
         0.  ,   4.16,   0.  ,   0.  ,   4.16,   4.16,   4.17,   8.34,
        -4.16,  -8.33, -12.5 , -12.5 , -15.83,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ])

# Improvement Score Bogota 2

In [33]:
diff2 = df2_phase4['Total Score'] - df2_phase3['Total Score']
diff2.values

array([  0.  ,  12.5 ,  12.5 ,  15.83,   7.5 ,  13.33,  15.63,  25.  ,
         1.67,   3.34, -14.17, -10.  ,  11.67,  32.5 ,  47.5 ,  45.84,
         7.5 ,   7.5 ,   4.17,  12.5 ,   4.17,   7.5 ,   5.  ,   3.34,
        -4.16,  -4.17,  -3.34,   0.  ,   4.17,   7.17,   6.67,   0.  ,
         0.  ,   0.  ,  -4.17, -30.  , -45.  ,   0.  ,   0.  ,   0.  ,
         0.  ])

# Improvement Score Bogota 1

In [34]:
diff1 = df1_phase4['Total Score'] - df1_phase3['Total Score']
diff1.values

array([  4.17,   5.  ,   0.41,  -6.25, -12.5 , -19.16, -21.04, -20.  ,
       -20.  , -15.83,  -4.17,  23.34,  30.42,  20.  ,  17.5 ,  19.58,
        20.83,  25.  ,  20.83,  45.83,  45.84,  40.83,  37.5 ,  40.  ,
        16.67,  15.84,   9.17,  12.5 ,  12.5 ,  20.83,  12.5 ,  15.83,
        24.17,  16.67,   8.33,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ])

# Improvement Score Bogota 0

In [35]:
diff0 = df0_phase4['Total Score'] - df0_phase3['Total Score']
diff0.values

array([ 20.  , -12.5 , -20.83,  -5.42,   6.66,  12.5 ,  15.83,  -0.84,
         1.67,   0.84,  25.  ,  16.67,  17.09,  18.33,   6.25,   0.  ,
         0.83,   7.5 ,  -0.83,  15.83,  21.67,  17.5 ,  12.5 ,  15.83,
        12.5 ,   4.17,   0.  ,   8.33,   0.  ,   0.  ,  25.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ])

In [36]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(diff0, diff1, diff2, diff3)
print(fvalue, pvalue)

2.354008067967665 0.07412063641290947


In [37]:
len(df0_phase4.index)

39

In [38]:
len(df0_phase3.index)

39

In [39]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'score': [ 20.  , -12.5 , -20.83,  -5.42,   6.66,  12.5 ,  15.83,  -0.84,
         1.67,   0.84,  25.  ,  16.67,  17.09,  18.33,   6.25,   0.  ,
         0.83,   7.5 ,  -0.83,  15.83,  21.67,  17.5 ,  12.5 ,  15.83,
        12.5 ,   4.17,   0.  ,   8.33,   0.  ,   0.  ,  25.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0. , 4.17,   5.  ,   0.41,  -6.25, -12.5 , -19.16, -21.04, -20.  ,
       -20.  , -15.83,  -4.17,  23.34,  30.42,  20.  ,  17.5 ,  19.58,
        20.83,  25.  ,  20.83,  45.83,  45.84,  40.83,  37.5 ,  40.  ,
        16.67,  15.84,   9.17,  12.5 ,  12.5 ,  20.83,  12.5 ,  15.83,
        24.17,  16.67,   8.33,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  , 0.  ,  12.5 ,  12.5 ,  15.83,   7.5 ,  13.33,  15.63,  25.  ,
         1.67,   3.34, -14.17, -10.  ,  11.67,  32.5 ,  47.5 ,  45.84,
         7.5 ,   7.5 ,   4.17,  12.5 ,   4.17,   7.5 ,   5.  ,   3.34,
        -4.16,  -4.17,  -3.34,   0.  ,   4.17,   7.17,   6.67,   0.  ,
         0.  ,   0.  ,  -4.17, -30.  , -45.  ,   0.  ,   0.  ,   0.  ,
         0.  , 28.33,  27.5 ,  11.67,  30.  ,  36.66,  20.  ,  34.17,  37.5 ,
        39.17,  35.83,  40.  ,  25.83,  26.67,  48.33,  37.5 ,  38.33,
        17.5 ,   5.  ,   5.84,   4.17,   9.16,  11.67,   0.  ,  -3.34,
         0.  ,   4.16,   0.  ,   0.  ,   4.16,   4.16,   4.17,   8.34,
        -4.16,  -8.33, -12.5 , -12.5 , -15.83,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ],
                   'group': np.repeat([0, 1, 2, 3], repeats=[39, 41, 41, 42])})

In [40]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd


# perform Tukey's test
tukey = pairwise_tukeyhsd(endog=df['score'],
                          groups=df['group'],
                          alpha=0.05)

#display results
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     0      1   4.6011 0.5523  -4.5313 13.7335  False
     0      2  -1.3416    0.9  -10.474  7.7908  False
     0      3     6.63  0.234  -2.4493 15.7092  False
     1      2  -5.9427 0.3214 -14.9602  3.0749  False
     1      3   2.0289    0.9  -6.9348 10.9926  False
     2      3   7.9715 0.1002  -0.9922 16.9352  False
-----------------------------------------------------


In [41]:
df0_phase2 = pd.read_csv('final-bogota-0-phase2.csv')
df0_phase2 = df0_phase2.loc[:, ~df0_phase2.columns.str.contains('^Unnamed')]
df0_phase2.head(5)

Project                Hack     Student  Total Score  \
0  capinillab  Bogota-Hack-0-2017  capinillab       247.50   
1   bsgarciac  Bogota-Hack-0-2017   bsgarciac       231.67   
2   mnguzmanc  Bogota-Hack-0-2017   mnguzmanc       220.00   
3   sacastroc  Bogota-Hack-0-2017   sacastroc       203.33   
4   camilo654  Bogota-Hack-0-2017   camilo654       195.00   

   The % of participants whose total score below your score      Phase  
0                                              98.04         2nd Phase  
1                                              96.08         2nd Phase  
2                                              94.12         2nd Phase  
3                                              92.16         2nd Phase  
4                                              90.20         2nd Phase

In [42]:
df1_phase2 = pd.read_csv('final-bogota-1-phase2.csv')
df1_phase2 = df1_phase2.loc[:, ~df1_phase2.columns.str.contains('^Unnamed')]
df1_phase2.head(5)

Project                Hack         Student  Total Score  \
0      dsbarrerag  Bogota-Hack-1-2017      dsbarrerag       333.33   
1      falperezgo  Bogota-Hack-1-2017      falperezgo       330.00   
2      daandradec  Bogota-Hack-1-2017      daandradec       313.33   
3  jesusfchavarro  Bogota-Hack-1-2017  jesusfchavarro       289.17   
4          oeroaq  Bogota-Hack-1-2017          oeroaq       288.33   

   The % of participants whose total score below your score      Phase  
0                                              97.67         2nd Phase  
1                                              95.35         2nd Phase  
2                                              93.02         2nd Phase  
3                                              90.70         2nd Phase  
4                                              88.37         2nd Phase

In [43]:
df2_phase2 = pd.read_csv('final-bogota-2-phase2.csv')
df2_phase2 = df2_phase2.loc[:, ~df2_phase2.columns.str.contains('^Unnamed')]
df2_phase2.head(5)

Project                Hack          Student  Total Score  \
0        fabianr23  Bogota-Hack-2-2017        fabianr23       330.00   
1  juasmartinezbel  Bogota-Hack-2-2017  juasmartinezbel       296.67   
2       JuanitoAli  Bogota-Hack-2-2017       JuanitoAli       284.17   
3     jscontrerasp  Bogota-Hack-2-2017       joaortizro       268.33   
4   cesarochoa2006  Bogota-Hack-2-2017   cesarochoa2006       255.83   

   The % of participants whose total score below your score      Phase  
0                                              97.62         2nd Phase  
1                                              95.24         2nd Phase  
2                                              92.86         2nd Phase  
3                                              90.48         2nd Phase  
4                                              88.10         2nd Phase

In [44]:
df3_phase2 = pd.read_csv('final-bogota-3-phase2.csv')
df3_phase2 = df3_phase2.loc[:, ~df3_phase2.columns.str.contains('^Unnamed')]
df3_phase2.head(5)

Project                Hack          Student  Total Score  \
0         dduartec  Bogota-Hack-3-2017         dduartec       333.33   
1    jumcorredorro  Bogota-Hack-3-2017    jumcorredorro       309.17   
2       lgmoralesa  Bogota-Hack-3-2017       lgmoralesa       268.33   
3  jscastelblancoh  Bogota-Hack-3-2017  jscastelblancoh       264.17   
4      lacardenasv  Bogota-Hack-3-2017      lacardenasv       264.17   

   The % of participants whose total score below your score      Phase  
0                                              97.62         2nd Phase  
1                                              95.24         2nd Phase  
2                                              92.86         2nd Phase  
3                                              88.10         2nd Phase  
4                                              88.10         2nd Phase

In [45]:
diff3 = df3_phase3['Total Score'] - df3_phase2['Total Score']
diff3.values

array([ -3.33,   0.83,  36.67,  10.83,   0.  ,   5.84, -11.25,  24.17,
        22.5 ,  15.  ,  13.33,   5.  ,  29.16,  10.  ,  12.5 ,  11.67,
        15.  ,  15.  ,  14.16,  16.67,  12.5 ,  10.  ,   8.33,   4.17,
         4.16,   0.84,   0.  ,   4.16,   0.  ,   4.17,   5.  ,   0.  ,
         0.  ,   3.33,   0.  ,   4.17,  15.83, -12.5 , -12.5 , -12.5 ,
       -12.5 ,   0.  ])

In [46]:
diff2 = df2_phase3['Total Score'] - df2_phase2['Total Score']
diff2.values

array([ 28.33,  24.16,  28.33,  36.67,  37.5 ,  32.5 ,  25.  ,  18.33,
        11.66,  11.66,  17.5 ,  12.5 ,   8.33,   5.84,  -5.84,  15.83,
        14.17,  12.5 ,  17.5 ,  10.83,  13.33,   4.17,  11.67,   9.16,
        12.5 ,  11.67,   4.17,   7.5 ,   4.16,   4.5 ,   5.  ,   8.33,
         7.5 ,  20.  ,   4.17,   4.17, -12.5 , -12.5 , -12.5 , -12.5 ,
       -12.5 ])

In [47]:
diff1 = df1_phase3['Total Score'] - df1_phase2['Total Score']
diff1.values

array([ 12.5 ,   8.33,  19.59,  35.83,  36.67,  54.58,  56.66,  53.33,
        73.33,  74.16,  70.84,  33.33,  38.75,  37.5 ,  39.17,  52.09,
        45.  ,  37.5 ,  24.17,   3.33,   0.  ,  -4.16,   8.34,   5.  ,
         4.16,   0.  ,   4.17,   4.16,   0.  ,  -8.33, -12.5 , -12.5 ,
       -12.5 , -16.67,  -8.33, -12.5 , -12.5 , -12.5 , -12.5 , -12.5 ,
         0.  ])

In [48]:
diff0 = df0_phase3['Total Score'] - df0_phase2['Total Score']
diff0.values

array([ 45.83,  57.5 ,  52.5 ,  47.09,  41.67,  40.  ,  35.84,  49.17,
        52.5 ,  70.  ,  49.16,  50.  ,  47.5 ,  47.5 ,  46.67,  45.  ,
        49.17,  28.33,  29.17,   9.17,   0.  ,   0.  ,  -0.83,   0.  ,
         0.  ,  -3.34, -12.5 ,  -0.83, -12.5 , -13.33, -62.5 , -33.33,
       -12.5 , -12.5 , -12.5 , -12.5 , -12.5 , -12.5 , -12.5 ])

In [49]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(diff0, diff1, diff2, diff3)
print(fvalue, pvalue)

2.2092158984491097 0.08913024033193412
